version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      npm-deps:
        patterns:
          - "*"
    ignore:
      # ignore all bootstrap major updates
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ava"
        update-types: ["version-update:semver-major"]
      - dependency-name: "chai"
        update-types: ["version-update:semver-major"]
      - dependency-name: "chai-as-promised"
        update-types: ["version-update:semver-major"]
