#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

import os
import json

with open('firefox/manifest.json', 'r') as fp:
    manifest = json.load(fp)
    version = ''.join(c for c in manifest['version'] if c in '0123456789.')

filename = 'cryptup-io-firefox-%s.zip' % version
os.system('rm -rf release/%s' % filename)
os.system('cd firefox && zip -rq ../release/%s ./* && cd ..' % filename)
print 'PACKED FIREFOX RELEASE INTO release/%s\n' % filename