#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

import os
import json

with open('firefox/manifest.json', 'r') as fp:
    manifest = json.load(fp)

filename = 'cryptup-io-firefox-%s.zip' % ''.join(c for c in manifest['version'] if c in '0123456789.')
os.system('rm -rf %s' % filename)
os.system('cd firefox && zip -rq ../%s ./* && cd ..' % filename)
print 'PACKED FIREFOX RELEASE INTO %s\n' % filename