#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

import os

os.system('./update_licence')
os.system('rm -rf cryptup-chrome.zip')
os.system('zip -rq cryptup-chrome.zip chrome/*')
print 'CHROME ---> cryptup-chrome.zip\n'
os.system('./../cryptup-test/chrome/test')