#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

import os
import sys
import json
import boto.s3.key

with open('config/release.json', 'r') as fp:
	config = json.load(fp)

with open('firefox/manifest.json', 'r') as fp:
	manifest = json.load(fp)
	version = ''.join(c for c in manifest['version'] if c in '0123456789.')

print "Uploading " + config['firefox']['path']['upload'] % version

with open(config['firefox']['path']['signed'] % version, 'r') as fp:
	s3conn = boto.connect_s3(config['aws']['id'], config['aws']['secret'])
	bucket = s3conn.get_bucket(config['aws']['bucket'])
	fp.seek(0, os.SEEK_END)
	size = fp.tell()
	k = boto.s3.key.Key(bucket)
	k.key = config['firefox']['path']['upload'] % version
	fp.seek(0)
	sent = k.set_contents_from_file(fp)
	if sent != size:
		raise Exception('File did not upload successfully')

hash = os.system('sha256sum ' + config['firefox']['path']['signed'] % version)

print "uploaded %s%s" % (config['aws']['base_url'], config['firefox']['path']['upload'] % version)
print "('%s', '%s')," % (version, hash)