name: Auto merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  dependabot:
    name: Approve and enable auto-merge
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'FlowCrypt/flowcrypt-browser'
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.FLOWCRYPT_ROBOT_ACCESS_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable squash auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.FLOWCRYPT_ROBOT_ACCESS_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
